name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      #
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          release_title: "What's Changed"
          changelog_file: "CHANGELOG.md"
          body: ${{ steps.generate_changelog.outputs.changelog }}